# 01. 넘파이 배열의 생성
---
* 날짜:
* 이름:


Numpy(Numerical Python)는 고성능 과학 계산을 위한 파이썬 패키지로 강렬한 N차원의 배열(array)을 제공합니다. 이 배열은 범용적인 데이터 처리에 사용 가능한 다차원 컨테이너라 할 수 있으며 파이썬의 list와 비슷하지만 더 빠르고 효율적으로 메모리를 관리합니다. 배열에 대한 여러가지 연산 등 처리를 제공하며 데이터과학의 핵심이라 할 수 있습니다.

https://numpy.org/



```
import numpy as np
```



In [ ]:
import numpy as np

## 개념정리
---



### **(1) 리스트 와 배열**

![](https://docs.sangyunlee.com/~/files/v0/b/gitbook-28427.appspot.com/o/assets%2F-LxaqUhwPNPE0iJCKfjJ%2F-MUgfOmYMQC2EJUN2rq_%2F-MUgttBGp-6BNnfXwC4R%2Fimage.png?alt=media&token=e3d4ca35-8fc8-473b-833a-f61ee70ab527)





* 리스트 생성

In [ ]:
a1= [2,5,6,9]
a2= [[3.5, 4.0, 6.5],[0.4, 0.9, 4.7]]
a3= [[[7,9,2],
      [4,0,8],
      [1,3,6],
      [5,8,4] ],
    [ [1,4,3],
      [0,0,0],
      [0,0,9],
      [0,0,7] ]]

#(4,3,2)     
a4=[ [[7,1],[9,4],[2,3]], [[4,0],[0,0],[8,0]], [[1,0],[3,0],[6,9]], [[5,0],[8,0],[4,7]] ]
#(3,2,4)

a5=[[[7,4,1,5],[1,0,0,0]], [[9,0,3,8],[4,0,0,0]], [[2,8,6,4],[3,0,9,7]]]

* 리스트를 넘파이 어레이로 변환

In [ ]:
a1 = np.array(a1)
a2 = np.array(a2)
a3 = np.array(a3)
a4 = np.array(a4)

* `.shape`: 배열의 shape 확인

In [ ]:
a1.shape, a2.shape, a3.shape ,a4.shape

((4,), (2, 3), (2, 4, 3), (4, 3, 2))

### **(2) 배열 초기화**




#### **1. `zeros()`**

배열의 모든 요소를 0으로 초기화 합니다.


```
배열 = np.zeros(shape)
```



In [ ]:
a= np.zeros(3)
a, a.shape

(array([0., 0., 0.]), (3,))

#### **2. `ones()`**

배열의 모든 요소를 1 로 초기화 합니다.
```
배열 = np.ones(shape)
```

In [ ]:
 a= np.ones(3)
 a, a.shape

(array([1., 1., 1.]), (3,))

#### **3. `full()`**

배열의 모든 요소를 지정 값으로 초기화 합니다.
```
배열 = np.full(shape, 지정값)
```

In [ ]:
 a= np.full(3,5)
 a, a.shape

(array([5, 5, 5]), (3,))

### **(3) 배열 생성**




#### **1. `eye()`**

단위행렬 (identity matrix)를 생성합니다. 단위 행렬이란 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬입니다.



```
배열 = np.eye(shape)
```



In [ ]:
a = np.eye(3)
a, a.shape

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]), (3, 3))

#### **2. `empty()`**

초기화되지 않은 배열을 생성합니다. 초기화 되지 않은 배열은 생성이 빠릅니다.

```
배열 = np.empty(정수)
```

In [ ]:
a = np.empty(3)
a, a.shape

(array([1., 1., 1.]), (3,))

#### **3. `_like()`**

특정 배열과 같은 shape가 같은 행렬을 생성합니다.

  * `np.zeros_like()`
  * `np.ones_like()`
  * `np.full_like()`
  * `np.empty_like()`

```
배열2  = np.()_like(배열1)
```


In [ ]:
b=np.zeros_like(a)
b, b.shape

(array([0., 0., 0.]), (3,))

### **(3) 생성한 값으로 배열 생성**




#### **1. `arange()`**

정수 범위의 배열을 생성합니다.

```
배열 = np.arange(start, end, step)
```


In [ ]:
a = np.arange(1,10,2)  #디폴트값은 입력안해도된다(0,10,1)
a,  a.shape       #1차원 배열밖에 안된다 

(array([1, 3, 5, 7, 9]), (5,))

#### **2. `linspace()`**

범위 내 균등 간격을 가지는 배열을 생성합니다.

```
배열  = np.linspace(start, end, bins)
```


In [ ]:
a = np.linspace(1,11,20)
a, a.shape

(array([ 1.        ,  1.52631579,  2.05263158,  2.57894737,  3.10526316,
         3.63157895,  4.15789474,  4.68421053,  5.21052632,  5.73684211,
         6.26315789,  6.78947368,  7.31578947,  7.84210526,  8.36842105,
         8.89473684,  9.42105263,  9.94736842, 10.47368421, 11.        ]),
 (20,))

#### **3. `logspace()`**

범위 내 균등 간격을 가지는 로그 스케일의 배열을 생성합니다.

```
배열2  = np.logspace(start, end, bins)
```


In [ ]:
a= np.logspace(2,125,10)
a, a.shape

(array([1.00000000e+002, 4.64158883e+015, 2.15443469e+029, 1.00000000e+043,
        4.64158883e+056, 2.15443469e+070, 1.00000000e+084, 4.64158883e+097,
        2.15443469e+111, 1.00000000e+125]), (10,))

### **(4) 랜덤값의 배열 생성**

| 함수 | 설명 |
|--|--|
| `seed` | 난수 발생을 위한 시드 지정|
| `permutation` | 순서 임의 변환, 임의의 순열 반환|
| `shuffle` | 리스트 또는 배열의 순서 섞기 |
| `random` | 랜덤값의 배열 생성|
| `rand` | 균등분포를 따르는 표본 추출|
| `randint` | 주어진 최소/최대 번위의 난수 추출 |
| `randn` | 표준정규분포를 따르는 표본 추출 |
| `binomial` | 이항분포를 따르는 표본 추출 |
| `normal` | 가우시안정규분포를 따르는 표본 추출 |
| `beta` | 베타분포를 따르는 표본 추출 |
| `chisquare` | 카이제곱분포를 따르는 표본 추출 |
| `gamma` | 감마분포를 따르는 표본 추출 |
| `uniform` | 균등분포를 따르는 표본 추출 |



#### **1. `rnadom.random()`**

랜덤 값을 지니는 배열을 생성합니다.



```
배열 = np.random.random(shape)
```



In [ ]:
a=np.random.random((2,3))
a,a.shape           #0부터 1사이의float값

(array([[0.75093353, 0.03904275, 0.61556174],
        [0.08397168, 0.48266557, 0.96672661]]), (2, 3))

#### **2. `random.randint()`**

일정 범위의 랜덤 정수값을 가지는 배열을 생성합니다.

```
배열 = np.random.randint(범위1, 범위2, shape)
```

In [ ]:
a= np.random.randint(0,10,shape)
a, a.shape

#### **3. `random.normal()`**
![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Standard_deviation_diagram.svg/350px-Standard_deviation_diagram.svg.png)





정규분포 (normal distribution) 을 따르는 랜덤 값 배열을 생성합니다. 정규분포의 평균은 0, 표준편차는 1입니다.

```
배열 = np.random.normal(평균, 표준편차, shape)
```

In [ ]:
 a=np.random.normal(2,1,(2,3))              #(0,1,shape)를 주면 표준정규분포가 된다
 a, a.shape

(array([[0.79782148, 1.47367034, 1.63174205],
        [1.33845447, 1.9162716 , 2.56892449]]), (2, 3))

#### **4. `random.rand()`**

균등분포 (unifrom distribution)을 따르는 랜덤한 수의 배열 생성합니다.

```
배열 = np.random.rand(shape)
```

In [ ]:
a= np.random.rand(10,2) #괄호없이 shape
a, a.shape

(array([[0.19302949, 0.59219315],
        [0.11611635, 0.26424245],
        [0.63191958, 0.44566988],
        [0.19081222, 0.31572618],
        [0.82976969, 0.96911412],
        [0.17923036, 0.14600447],
        [0.48908159, 0.71648343],
        [0.98353165, 0.46274427],
        [0.49435468, 0.29782162],
        [0.54976867, 0.09460183]]), (10, 2))

#### **5. `random.randn()`**

표준 정규 분포(standard normal distribution)를 따르는 랜덤한 수의 배열을 생성합니다.

```
배열 = np.random.randn(shape)
```

In [ ]:
a = np.random.randn(3,2)
a , a.shape

(array([[-1.36036427,  0.85000741],
        [-0.25853834, -0.36268114],
        [-1.71877131,  0.28169901]]), (3, 2))

### **(5) 데이터 타입**

| 함수 | 설명 |
|--|--|
| `bool_` | 불리언(Boolean) 값. True, False 값을 지님|
| `int_` | 정수 (integer)|
| `intc` |  c 언어에서 사용되는 `int` 와 동일 |
| `intp` | 인덱싱에 사용되는 정수 |
| `int8` | 바이트(Byte)(-128 ~ 127)|
| `int16` | 정수 |
| `int32` | 정수|
| `int64` | 정수 |
| `uint8` | 부호없는 정수 (0~ 255) |
| `uint16` | 부호없는 정수  |
| `uint32` | 부호없는 정수  |
| `uint64` | 부호없는 정수 |
| `float16` | 반정밀 부동 소수점(Yalf precision float) |
| `float32` | 단정밀 부동 소수점(Single precision float)|
| `float64` | 배정밀 부동 소수점(Double precision float)|
| `float_` | =`float64` |
| `complex64` | 복소수, 두개의 32비트 부동 소수점으로 표현|
| `complex128` | 복소수, 두개의 64비트 부동 소수점으로 표현 |
| `complex_` | =`complex128` |





```
배열 = np.생성(dtype=타입)
```



In [ ]:
a = np.random.random((2,3))
print(a,a.shape)
a = np.array(a, dtype='float16')
print(a, a.shape)   #보통은 디폴트 값인 float32를 쓴다

[[0.19359563 0.25409728 0.21488831]
 [0.67668945 0.12909305 0.87824212]] (2, 3)
[[0.1936 0.2542 0.2148]
 [0.677  0.1292 0.8784]] (2, 3)


## 예제
---

####**예제 01**

아래 그림의 값과 shape를 가지는 데이터 배열을 생성하고 출력하세요. 그림에서 보이지 않는 값들은 0으로 정의하세요

![](https://ichi.pro/assets/images/max/724/1*X0Dg7QfSYtWhSAu-afi8-g.png)




* 1D array

In [ ]:
d1=[3,2]

* 2D array

In [ ]:
d2=[[1,0,1],[3,4,1]]

* 3D array

In [ ]:
d3=[[[1,7,9],[5,9,3],[7,9,9]],
    [[0,0,0],[0,0,0],[0,0,0]]]

####**예제 02**

**예제01** 에서 만든 1d 배열의 shape와 똑같은 shape를 가지는 배열을 만드세요, 단 모든 값은 1입니다. 


In [ ]:
np.ones_like(d1)

array([1, 1])

####**예제 03**

**예제01** 에서 만든 2d 배열의 shape와 똑같은 shape를 가지는 배열을 만들고 출력하세요, 단 모든 값은 0입니다. 


In [ ]:
np.zeros_like(d2)

array([[0, 0, 0],
       [0, 0, 0]])

####**예제 04**

**예제01** 에서 만든 3d 배열의 shape와 똑같은 shape를 가지는 배열을 만들고 출력하세요, 단 모든 값은 10입니다.


In [ ]:
np.full_like((d3),10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

####**예제 05**

1에서 100까지 홀수값만을 가지는 배열을 `np.arrange`를 이용해 만드세요


In [ ]:
a=np.arange(1,100,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

####**예제 06**

1에서 100까지 홀수값만을 가지는 배열을 `np.linspace`를 이용해 만드세요


In [ ]:
a=np.linspace(1,99,50,dtype=int)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

####**예제 07**

shape가 (5,5)인 단위행렬(Identity matrix)를 생성하고 출력하세요


In [ ]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

####**예제 08**

shape가 (1,5,5)인 배열을 생성하고 출력하세요. 단 배열은 균등분포를 따르는 랜덤값입니다.


In [ ]:
a= np.random.rand(1,5,5)
a

array([[[0.54778873, 0.12151786, 0.11542957, 0.72777891, 0.15877238],
        [0.28113515, 0.51158219, 0.64163547, 0.60561978, 0.86954111],
        [0.71183283, 0.82099892, 0.20754314, 0.53797422, 0.15955382],
        [0.38682311, 0.02188554, 0.09854854, 0.17695926, 0.989687  ],
        [0.29341036, 0.34007588, 0.83266183, 0.06926866, 0.90196731]]])

####**예제 09**

shape가 (2,2,2)인 배열을 생성하고 출력하세요. 단 배열은 표준정규분포 를 따르는 랜덤값입니다.


In [ ]:
a=np.random.randn(2,2,2)
a

array([[[-0.61981645,  0.33961839],
        [ 0.23182098, -0.18725457]],

       [[-0.74827889, -0.71534002],
        [ 0.82354835, -0.32663649]]])

####**예제 10**

**예제01** 에서 만든 배열들의 shape와 데이터 type을 확인하세요. 1d, 2d, 3d 배열의 타입을 각각 int64, float64, uint8로 변경한 배열을 생성하고 타입을 확인하세요

In [ ]:
d1_change=np.array(d1,dtype='int64')
d2_change=np.array(d2,dtype='float64')
d3_change=np.array(d3,dtype='uint8')
print(d1_change.shape,d1_change.dtype,"\n")
print(d2_change.shape,d2,d2_change.dtype,"\n")
print(d3_change.shape,d3,d3_change.dtype,"\n")


(2,) int64 

(2, 3) [[1 0 1]
 [3 4 1]] float64 

(2, 3, 3) [[[1, 7, 9], [5, 9, 3], [7, 9, 9]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]] uint8 

