# 03. 넘파이: 배열구조 다루기
---
* 날짜:
* 이름:


Numpy(Numerical Python)는 고성능 과학 계산을 위한 파이썬 패키지로 강렬한 N차원의 배열(array)을 제공합니다. 이 배열은 범용적인 데이터 처리에 사용 가능한 다차원 컨테이너라 할 수 있으며 파이썬의 list와 비슷하지만 더 빠르고 효율적으로 메모리를 관리합니다. 배열에 대한 여러가지 연산 등 처리를 제공하며 데이터과학의 핵심이라 할 수 있습니다.




**참고사이트**
>  * [NumPy](https://numpy.org/)
>  * [NumPy Illustrated](https://www.mybluelinux.com/numpy-illustrated-the-visual-guide-to-numpy/
)
> 

```
import numpy as np
```



In [ ]:
import numpy as np

## 개념정리
---



---
### **(1) 배열 shape 변경**
---




#### **1. `T` 전치 (transopose)**


<p align='center'>
<img src=https://www.mybluelinux.com/img/post/posts/0123/NumPy-Illustrated-30.webp width=750>
</p>

```
배열2 = 배열1.T
```








In [ ]:
a = np.arange(1,7).reshape(2,3)
print(a,a.shape)
a_t =a.T
print(a_t,a_t.shape)

a_t2=np.transpose(a)  ##두가지방법 x.T // np.transpose(x)
print(a_t2,a_t2.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 4]
 [2 5]
 [3 6]] (3, 2)
[[1 4]
 [2 5]
 [3 6]] (3, 2)


In [ ]:
b = np.arange(1,4).reshape(1,3)
print(b)

b_t=b.T
print(b_t,b_t.shape)

b_t2=np.transpose(b)
print(b_t2,b_t2.shape)

[[1 2 3]]
[[1]
 [2]
 [3]] (3, 1)
[[1]
 [2]
 [3]] (3, 1)


In [ ]:
c = np.arange(1,4).reshape(3,)
print(c,c.shape)

c_t=c.T
print(c_t,c_t.shape)

c_t2=np.transpose(c)
print(c_t2,c_t2.shape)

[1 2 3] (3,)
[1 2 3] (3,)
[1 2 3] (3,)


#### **2. `swap()`**

<p align='center'>
<img src=https://www.mybluelinux.com/img/post/posts/0123/NumPy-Illustrated-58.webp width=650>
</p>

```
배열2 = 배열1.swapaxes(축1, 축2)
```







In [ ]:
 a = np.arange(1,25).reshape(2,4,3)
 print((a,a.shape))

 a=np.swapaxes(a,0,1)          #a의 shape가 바뀐다 
 print(a,a.shape)

(array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]]), (2, 4, 3))
[[[ 1  2  3]
  [13 14 15]]

 [[ 4  5  6]
  [16 17 18]]

 [[ 7  8  9]
  [19 20 21]]

 [[10 11 12]
  [22 23 24]]] (4, 2, 3)


In [ ]:
 a = np.arange(1,25).reshape(2,4,3)
 print((a,a.shape))

 a=np.swapaxes(a,0,2)          #a의 shape가 바뀐다 
 print(a,a.shape)

(array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]]), (2, 4, 3))
[[[ 1 13]
  [ 4 16]
  [ 7 19]
  [10 22]]

 [[ 2 14]
  [ 5 17]
  [ 8 20]
  [11 23]]

 [[ 3 15]
  [ 6 18]
  [ 9 21]
  [12 24]]] (3, 4, 2)


#### **3. `reshape()`**


```
배열2 = 배열1.reshape(shape)
```

```
a =  np.zeros((2,3,5))
print(a, a.shape)
a_reshape = a.reshape((3,2,5))
print(a_reshape, a_reshape.shape)
```




In [ ]:
a =  np.arange(30).reshape(2,3,5)
print(a, a.shape)
a_reshape = a.reshape((3,2,5))
a_swap=np.swapaxes(a,0,1)
print(a_reshape, a_reshape.shape)
print(a_swap,a_swap.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] (2, 3, 5)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)
[[[ 0  1  2  3  4]
  [15 16 17 18 19]]

 [[ 5  6  7  8  9]
  [20 21 22 23 24]]

 [[10 11 12 13 14]
  [25 26 27 28 29]]] (3, 2, 5)


#### **4. `resize()`**

`resize()` 함수는 shape 크기를 증가시킬수도 있고 감소 시킬수도 있습니다. 다만 증가시킬 때는 빈 공간을 0으로 채우고 감소할 때는 사이즈에 포함되지 않는 값은 삭제됩니다.


```
배열1.resize(shape)
```

```
a =  np.arange(1,16)
print(a, a.shape)
a.resize((3,5))
print(a, a.shape)
a.resize((3,8))
print(a, a.shape)
a.resize((3,2))
print(a, a.shape)
```



In [ ]:
a =  np.arange(1,16) ###reshape는 개수와 차원이 맞아야되지만 resize는 알아서 채우고(0) 줄여준다(끝값 삭제)
print(a, a.shape)
a.resize((3,5))
print(a, a.shape)
a.resize((3,8))
print(a, a.shape)
a.resize((3,2))
print(a, a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] (15,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] (3, 5)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15  0]
 [ 0  0  0  0  0  0  0  0]] (3, 8)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


---
### **(2) 배열 추가**
---






#### **1. `append()`**



<p align='center'>
<img src=https://www.mybluelinux.com/img/post/posts/0123/NumPy-Illustrated-39.webp width=650>
</p>


`axis` 지정이 없다면 1차원 배열 형태로 변형되어 결합합니다. `axis`를 n으로 지정시 `shape[n]`을 제외한 나머지 shape는 같아야 합니다.

```
배열3 = np.append(배열1, 배열2)
```






In [ ]:
a=np.arange(1,16).reshape(3,5)
print(a,a.shape)
b= np.ones(5).reshape(1,5)
print(b,b.shape)
c=np.append(a,b,axis=0)
print(c,c.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] (3, 5)
[[1. 1. 1. 1. 1.]] (1, 5)
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [ 1.  1.  1.  1.  1.]] (4, 5)


In [ ]:
a=np.arange(1,16).reshape(3,5)
print(a,a.shape)
b= np.zeros((3,2))
print(b,b.shape)
c=np.append(a,b,axis=1)
print(c,c.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] (3, 5)
[[0. 0.]
 [0. 0.]
 [0. 0.]] (3, 2)
[[ 1.  2.  3.  4.  5.  0.  0.]
 [ 6.  7.  8.  9. 10.  0.  0.]
 [11. 12. 13. 14. 15.  0.  0.]] (3, 7)


#### **2. `concatenate()`**

<p align='center'>
<img src=https://www.mybluelinux.com/img/post/posts/0123/NumPy-Illustrated-56.webp width=650>
</p>

```
배열3 = np.concatenate([배열1, 배열2], axis=기준축)

a = np.arange(1,25).reshape(2,3,4)
print("a\n",a,a.shape)

b = np.arange(1,17).reshape(2,2,4)
print("a\n",b,b.shape)

c = np.arange(1,13).reshape(2,3,2)
print("a\n",c,c.shape)

d = np.arange(1,25).reshape(2,3,4)
print("a\n",d,d.shape)

```




In [ ]:
a = np.arange(1,25).reshape(2,3,4)
print("a\n",a,a.shape)

b = np.arange(1,17).reshape(2,2,4)
print("a\n",b,b.shape)

c = np.arange(1,13).reshape(2,3,2)
print("a\n",c,c.shape)

d = np.arange(1,25).reshape(2,3,4)
print("a\n",d,d.shape)


a
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] (2, 3, 4)
a
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] (2, 2, 4)
a
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
a
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] (2, 3, 4)


In [ ]:
new_arr = np.concatenate([a,b],axis=1)
print(new_arr,new_arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [ 1  2  3  4]
  [ 5  6  7  8]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]
  [ 9 10 11 12]
  [13 14 15 16]]] (2, 5, 4)


In [ ]:
new_arr = np.concatenate([a,d],axis=0)
print(new_arr,new_arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] (4, 3, 4)


In [ ]:
new_arr = np.concatenate([a,c],axis=2)
print(new_arr,new_arr.shape)

[[[ 1  2  3  4  1  2]
  [ 5  6  7  8  3  4]
  [ 9 10 11 12  5  6]]

 [[13 14 15 16  7  8]
  [17 18 19 20  9 10]
  [21 22 23 24 11 12]]] (2, 3, 6)


---
### **(3) 배열 쌓기**
---

<p align='center'>
<img src=https://www.mybluelinux.com/img/post/posts/0123/NumPy-Illustrated-55.webp width=600>
</p>




In [ ]:
a = np.arange(1,25).reshape(3,4,2)
print("a\n",a,a.shape)
b = np.arange(1,17).reshape(2,4,2)
print("b\n",b,b.shape)
c = np.arange(1,13).reshape(3,2,2)
print("c\n",c,c.shape)
d = np.arange(1,25).reshape(3,4,2)
print("d\n",d,d.shape)

a
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]] (3, 4, 2)
b
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] (2, 4, 2)
c
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] (3, 2, 2)
d
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]] (3, 4, 2)


####**1. `hstack()`**

수평으로 배열을 쌓습니다.(axis=1)

```
배열3 = np.hstack([배열1, 배열2])
```


In [ ]:
new_arr = np.hstack([a,c])
print(a.shape,c.shape)
print(new_arr,new_arr.shape)

(3, 4, 2) (3, 2, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 1  2]
  [ 3  4]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]
  [ 5  6]
  [ 7  8]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]
  [ 9 10]
  [11 12]]] (3, 6, 2)


####**2. `vstack()`**

수직으로 배열을 쌓습니다.(axis=0)
```
배열3 = np.vstack([배열1, 배열2])
```


In [ ]:
new_arr = np.vstack([a,b])
print(a.shape,c.shape)
print(new_arr,new_arr.shape)

(3, 4, 2) (3, 2, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] (5, 4, 2)


####**3. `dstack()`**

새로운 축으로 배열을 쌓습니다.(axis=2)
```
배열3 = np.dstack([배열1, 배열2])
```


In [ ]:
a0 =np.zeros((3,2))
a1=np.ones((3,2))

new_arr = np.dstack([a0,a1])
print(a0.shape,a1.shape)
print(new_arr,new_arr.shape)

(3, 2) (3, 2)
[[[0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]]] (3, 2, 2)


####**4. `stack()`**

새로운 축으로 배열을 쌓습니다.
```
배열3 = np.stack([배열1, 배열2])
```

In [ ]:
a0 =np.zeros((3,2))
a1=np.ones((3,2))

new_arr = np.stack([a0,a1])
print(a0.shape,a1.shape)
print(new_arr,new_arr.shape)

(3, 2) (3, 2)
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]] (2, 3, 2)


---
### **(4) 배열 분할**
---

<p align='center'>
<img src=https://www.mybluelinux.com/img/post/posts/0123/NumPy-Illustrated-35.webp  width=650>
</p>



In [ ]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(1,9).reshape(2,4)
c = np.arange(1,7).reshape(3,2)
print(a.shape,b.shape,c.shape)

(3, 4) (2, 4) (3, 2)


#### **1. `split()`**


```
배열n1, .. 배열nm = np.split(배열, [n1, .. nm], axis=축)
```










#### **2. `vsplit()`**

수직 방향으로 배열을 분할합니다.

```
배열n1, .. 배열nm = np.vsplit(배열, [n1, .. nm]
```




In [ ]:
print(a.shape,b.shape)
new_arr=np.vstack((a,b))
print(new_arr,new_arr.shape)
new_arr0, new_arr1 =np.vsplit(new_arr,[3]) 
print(new_arr0)
print(new_arr1)

(3, 4) (2, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]] (5, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]


#### **3. `hsplit()`**

수평방향으로 축을 분할합니다.

```
배열n1, .. 배열nm = np.hsplit(배열, [n1, .. nm]
```

In [ ]:
print(a.shape,c.shape)
new_arr=np.hstack((a,c))
print(new_arr,new_arr.shape)
new_arr0, new_arr1 =np.hsplit(new_arr,[3]) 
print(new_arr0,new_arr0.shape)
print(new_arr1,new_arr1.shape)

(3, 4) (3, 2)
[[ 1  2  3  4  1  2]
 [ 5  6  7  8  3  4]
 [ 9 10 11 12  5  6]] (3, 6)
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]] (3, 3)
[[ 4  1  2]
 [ 8  3  4]
 [12  5  6]] (3, 3)


## 예제
---

####**예제 01**

모든 요소가 1이고 `(3,3,2)` shape를 가지는 3차원 배열을 생성하고 출력 및 shape를 확인하세요

In [ ]:
a=np.ones((3,3,2))
print(a,a.shape)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]] (3, 3, 2)


**01-1**

shape가 `(3,6)`인 2차원 배열로 변경하고 배열 출력 및 shape를 확인하세요 

In [ ]:
a=a.reshape(3,6)
print(a1,a1.shape)

[[[0 1]]

 [[6 7]]] (2, 1, 2)


**01-2**

배열을 transpose 하고 배열 출력 및 shape를 확인하세요

In [ ]:
a1_t=a1.T
print(a1_t,a1_t.shape)

[[[0 6]]

 [[1 7]]] (2, 1, 2)


**01-3**

shape를 늘려 `(3,8)`인 2차원 배열로 변경하고  배열 출력 및 shape를 확인하세요 

In [ ]:
a=np.ones((3,3,2))
print(a,a.shape)
a.resize((3,8))
print(a,a.shape)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]] (3, 3, 2)
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0.]] (3, 8)


**01-4**

shape가 `(1,3,8)`인 3차원 배열로 변경하고  배열 출력 및 shape를 확인하세요 

In [ ]:
a.resize((1,3,8))
print(a,a.shape)

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 0. 0. 0. 0. 0. 0.]]] (1, 3, 8)


####**예제 02**

아래 표와 같은 2차원 배열을 생성하세요

* 배열1

|||
|--|--|
|0|1|
|2|3|
|4|5|

* 배열2

|||
|--|--|
|6|7|
|8|9|
|10|11|

* 배열3

|||
|--|--|
|12|13|
|14|15|
|16|17|

In [ ]:
a1=np.array([[0,1],[2,3],[4,5]])
a2=np.array([[6,7],[8,9],[10,11]])
a3=np.array([[12,13],[14,15],[16,17]])

**02-1**

위에서 생성한 배열1과 배열2 합쳐 shape가 `(3,2,2)` 인 배열을 만드세요

In [ ]:
print(a1.shape,a2.shape)

a1a2 = np.dstack([a1,a2])
print(a1a2,a1a2.shape)

(3, 2) (3, 2)
[[[ 0  6]
  [ 1  7]]

 [[ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]]] (3, 2, 2)


**02-2**

위에서 생성한 배열1과 배열2 합쳐 shape가 `(2,3,2)` 인 배열을 만드세요

In [ ]:
print(a1.shape,a2.shape)

a1a2 = np.stack([a1,a2])
print(a1a2,a1a2.shape)

(3, 2) (3, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] (2, 3, 2)


**02-3**

위에서 생성한 배열1, 배열2, 배열3을 합쳐 shape가 `(2,3,3)` 인 배열을 만드세요

In [ ]:
print(a1.shape,a2.shape,a3.shape)

a1a2a3 = np.stack((a1,a2,a3)).T
print(a1a2a3,a1a2a3.shape)

(3, 2) (3, 2) (3, 2)
[[[ 0  6 12]
  [ 2  8 14]
  [ 4 10 16]]

 [[ 1  7 13]
  [ 3  9 15]
  [ 5 11 17]]] (2, 3, 3)


**02-4**

**02-2**에서 만든 배열을 `axis=1`을 기준으로 총 3개의 배열로 나누세요

In [ ]:
a_1,a_2,a_3=np.hsplit(a1a2,[1,2])
print(a_1,a_1.shape)
print(a_2,a_2.shape)
print(a_3,a_3.shape)


[[[0 1]]

 [[6 7]]] (2, 1, 2)
[[[2 3]]

 [[8 9]]] (2, 1, 2)
[[[ 4  5]]

 [[10 11]]] (2, 1, 2)


####**예제 03**

아래 그림을 차례대로 만족하는 코드를 작성하세요

<p align='center'>
<img src=https://codetorial.net/numpy/_images/numpy_transpose_02.png width=400>
</p>

In [ ]:
a=np.arange(1,7).reshape(2,3)
a=a.T
print(a,a.shape)

[[1 4]
 [2 5]
 [3 6]] (3, 2)


####**예제 04**

아래 그림을 차례대로 만족하는 코드를 작성하세요


<p align="center">
<img src=https://www.w3resource.com/w3r_images/python-numpy-image-exercise-150.svg width="200">
</p>

In [ ]:
arr=np.arange(0,12).reshape(3,4)

a,arr=np.hsplit(arr,[1])
b,arr=np.hsplit(arr,[1])

arr=np.hstack([a,arr])
arr=np.hstack([b,arr])
print(arr)

[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


####**예제 05**

아래 그림을 차례대로 만족하는 코드를 작성하세요


<p align="center">
<img src=https://blog.kakaocdn.net/dn/Kv3wG/btqHjprfZmj/AovG4uJwyTKWPUJkOkIGK1/img.png width="450">
</p>

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
ab=np.hstack([a,b])
print(ab,ab.shape)
c=np.array([[1],[2],[3]])
d=np.array([[4],[5],[6]])
cd=np.hstack([c,d])
print(cd,cd.shape)

[1 2 3 4 5 6] (6,)
[[1 4]
 [2 5]
 [3 6]] (3, 2)


####**예제 06**
아래 그림을 차례대로 만족하는 코드를 작성하세요


<p align="center">
<img src=https://blog.kakaocdn.net/dn/HIXPd/btqHbZtp0tx/31CVtA3pFnjHYhrEwCra3K/img.png width="450">
</p>

In [ ]:
arr=np.arange(1,9).reshape(4,2)
a,b=np.vsplit(arr,[2])
a=a.reshape(1,2,2)
b=b.reshape(1,2,2)
ab=np.hstack([a,b])
ab=ab.reshape(2,2,2)
print(ab)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


####**예제 07**
아래 그림을 차례대로 만족하는 코드를 작성하세요


<p align="center">
<img src=https://blog.kakaocdn.net/dn/egRNlA/btqHgqxlRKn/nklzYhNUqjOB8wf2edXiAk/img.png width="450">
</p>

In [ ]:
arr=np.arange(1,9).reshape(4,2)
a,b=np.vsplit(arr,[2])
c,d=np.vsplit(arr,[2])

a.reshape(2,1,2)
b.reshape(2,1,2)
c.reshape(2,2,1)
d.reshape(2,2,1)

ab=np.stack([a,b])
cd=np.dstack([c,d])

print(ab.shape)
print(cd.shape)


(2, 4)
(2, 2, 2)


####**예제 08**
아래 그림을 차례대로 만족하는 코드를 작성하세요


<p align="center">
<img src=https://www.w3resource.com/w3r_images/numpy-manipulation-stack-function-image-1.png width="150">
</p>

In [ ]:
a=np.array([2,3,4])
b=np.array([3,4,5])
ab=np.stack([a,b])
print(ab.shape)

(2, 3)


####**예제 09**
아래 그림을 차례대로 만족하는 코드를 작성하세요


<p align="center">
<img src=https://www.w3resource.com/w3r_images/numpy-manipulation-stack-function-image-2.png width="150">
</p>

In [ ]:
a=np.array([2,3,4])
b=np.array([3,4,5])
ab=np.stack((a, b), axis=-1)
print(ab,ab.shape)

[[2 3]
 [3 4]
 [4 5]] (3, 2)
